[env:cardputer-adv]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 1500000
monitor_speed = 115200

build_flags =
  -DESP32S3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DCORE_DEBUG_LEVEL=0

board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi

lib_deps =
  schreibfaul1/ESP32-audioI2S @ ^3.0.0
  m5stack/M5Unified @ ^0.1.17
  m5stack/M5GFX @ ^0.1.16
